version: "3.9"
services:
 system-service:
  image: dennisraaijmakers/api_eindproject_dr_2ccs01
  ports:
    - "8000:8000"
  volumes:
    - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume: